name: doctor_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.3.11
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets_manager.dart  

flutter:
  uses-material-design: true
  
  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/

  
    # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
